# Generated by Django 6.0.3 on 2026-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
