# Generated by Django 6.0.3 on 2026-03-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_accounts', '0002_communityprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('CREATOR', 'Creator'), ('TEAM', 'Team')], default='TEAM', max_length=10),
        ),
    ]
