# Generated by Django 6.0.3 on 2026-03-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
